name: CI/CD Pipeline mchacana

on:
  push:
    branches:
      - master
      - feature-ms-miguelChacana-branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Dar permisos de ejecución a gradlew
      run: |
        chmod +x ./gradlew
      shell: bash

    - name: Build
      run: |
        # Limpia y construye el proyecto con Gradle
        ./gradlew clean build

        # ejecuta pruebas unitarias
        ./gradlew test

    - name: Code Review
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        # Descargar SonarScanner
        curl -L -o sonarscanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
        unzip sonarscanner-cli.zip
        export PATH=$PWD/sonar-scanner-4.6.2.2472-linux/bin:$PATH

        # Ejecutar el análisis de SonarCloud
        sonar-scanner \
          -Dsonar.login=${SONAR_TOKEN} \
          -Dsonar.projectKey=mchacana22_article_dec_28_mavengradle-based-multi-module-spring-boot-microservices \
          -Dsonar.organization=mchacana22 \
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.sources=.

      shell: bash


    - name: Deploy
      run: |
        # Configura el despliegue a tu contenedor aquí

    - name: Test
      run: |
        # Realiza pruebas de rendimiento con JMeter u otras herramientas.
        # Ejecuta pruebas de aceptación con Postman.

    - name: Generate PDF
      run: |
        # Genera un PDF de evidencia del quiebre.

    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: evidence-pdf
        path: path/al/pdf/generado.pdf
